#!/usr/bin/expect -f
## wrapper to make passwd(1) be non-interactive
## username is passed as 1st arg, passwd as 2nd
#

set username [lindex $argv 0]
set password [lindex $argv 1]
set newpassword [lindex $argv 2]

set count $argc
while {$argc ==  3}  {
	set count 4
	set fp [open serverfile r]
	while {[gets $fp line] >= 0} {
		puts "$username $password $newpassword"
		set machine [string trim $line]
		puts "SSH over to $machine"
		spawn ssh -q $machine passwd
		expect "password:"
		send "$password\r"
		expect "password:"
		send "$newpassword\r"
		expect "password:"
		send "$newpassword\r"
		expect eof
	}
	close $fp
}
if {$count != 3}  {
	puts "Please call script providing three parameters"
	puts "\"Username\" \"Old Password\" \"New Password\""
}
